package com.microstock.media.service;

import com.microstock.common.domain.WorkflowStatus;
import com.microstock.common.error.ApiException;
import com.microstock.common.security.OwnershipGuard;
import com.microstock.common.security.SecurityUtils;
import com.microstock.concept.domain.Concept;
import com.microstock.concept.repository.ConceptRepository;
import com.microstock.keyword.domain.Keyword;
import com.microstock.keyword.repository.KeywordRepository;
import com.microstock.masterdata.domain.CaptureDevice;
import com.microstock.masterdata.domain.Lens;
import com.microstock.masterdata.repository.CaptureDeviceRepository;
import com.microstock.masterdata.repository.LensRepository;
import com.microstock.media.domain.MediaAsset;
import com.microstock.media.repository.MediaAssetRepository;
import com.microstock.media.repository.MediaSpecifications;
import com.microstock.media.web.dto.MediaFilter;
import com.microstock.media.web.dto.MediaRequest;
import com.microstock.media.web.dto.MediaResponse;
import com.microstock.media.web.dto.MediaSummaryResponse;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class MediaService {

    private final MediaAssetRepository mediaRepository;
    private final CaptureDeviceRepository captureDeviceRepository;
    private final LensRepository lensRepository;
    private final ConceptRepository conceptRepository;
    private final KeywordRepository keywordRepository;
    private final OwnershipGuard ownershipGuard;

    @PersistenceContext
    private EntityManager entityManager;

    public MediaService(
            MediaAssetRepository mediaRepository,
            CaptureDeviceRepository captureDeviceRepository,
            LensRepository lensRepository,
            ConceptRepository conceptRepository,
            KeywordRepository keywordRepository,
            OwnershipGuard ownershipGuard) {
        this.mediaRepository = mediaRepository;
        this.captureDeviceRepository = captureDeviceRepository;
        this.lensRepository = lensRepository;
        this.conceptRepository = conceptRepository;
        this.keywordRepository = keywordRepository;
        this.ownershipGuard = ownershipGuard;
    }

    @Transactional
    public MediaResponse create(MediaRequest req) {
        UUID ownerId = SecurityUtils.currentUserId();
        MediaAsset media = new MediaAsset(ownerId, req.title().trim(), req.mediaType());
        applyScalarFields(media, req);
        applyDevice(media, req, ownerId, true);
        applyLens(media, req);
        applyConcepts(media, req, ownerId);
        applyKeywords(media, req, ownerId);
        validateStatusRequirements(media);
        MediaAsset saved = mediaRepository.save(media);
        // The business code is generated by a DB default; refresh to read it back.
        entityManager.flush();
        entityManager.refresh(saved);
        return MediaResponse.from(saved);
    }

    @Transactional(readOnly = true)
    public MediaResponse get(UUID id) {
        MediaAsset media = loadOwned(id);
        return MediaResponse.from(media);
    }

    @Transactional
    public MediaResponse update(UUID id, MediaRequest req) {
        MediaAsset media = loadOwned(id);
        UUID ownerId = media.getOwnerId(); // ownership never changes on update
        media.setTitle(req.title().trim());
        media.setMediaType(req.mediaType());
        applyScalarFields(media, req);
        applyDevice(media, req, ownerId, false);
        applyLens(media, req);
        applyConcepts(media, req, ownerId);
        applyKeywords(media, req, ownerId);
        validateStatusRequirements(media);
        return MediaResponse.from(media);
    }

    @Transactional
    public void softDelete(UUID id) {
        MediaAsset media = loadOwned(id);
        if (!media.isDeleted()) {
            media.setDeletedAt(java.time.Instant.now());
        }
    }

    @Transactional
    public MediaResponse restore(UUID id) {
        MediaAsset media = loadOwnedIncludingDeleted(id);
        media.setDeletedAt(null);
        return MediaResponse.from(media);
    }

    @Transactional(readOnly = true)
    public Page<MediaSummaryResponse> search(MediaFilter filter, Pageable pageable) {
        var spec = MediaSpecifications.build(filter, SecurityUtils.currentUserId(), ownershipGuard.isAdmin());
        return mediaRepository.findAll(spec, pageable).map(MediaSummaryResponse::from);
    }

    @Transactional(readOnly = true)
    public Page<MediaSummaryResponse> listDeleted(Pageable pageable) {
        return mediaRepository
                .findByOwnerIdAndDeletedAtIsNotNull(SecurityUtils.currentUserId(), pageable)
                .map(MediaSummaryResponse::from);
    }

    // ----------------------------------------------------------------------
    // Internals
    // ----------------------------------------------------------------------

    /** Loads a non-deleted asset and enforces ownership (404 on miss/denied). */
    private MediaAsset loadOwned(UUID id) {
        MediaAsset media = mediaRepository.findWithDetailsById(id)
                .orElseThrow(() -> ApiException.notFound("Media not found"));
        ownershipGuard.assertCanAccess(media);
        return media;
    }

    private MediaAsset loadOwnedIncludingDeleted(UUID id) {
        return loadOwned(id); // findWithDetailsById includes deleted rows
    }

    private void applyScalarFields(MediaAsset media, MediaRequest req) {
        media.setThumbnailKey(blankToNull(req.thumbnailKey()));
        media.setDescription(req.description());
        media.setNotes(req.notes());
        media.setCaptureDate(req.captureDate());
        media.setLocation(req.location());
        media.setContentUsageType(req.contentUsageType());
        media.setWorkflowStatus(req.workflowStatus() == null ? WorkflowStatus.DRAFT : req.workflowStatus());
        media.setOriginalFilePath(req.originalFilePath());
        media.setExportFilePath(req.exportFilePath());
        media.setStorageType(req.storageType());
        media.setAiGenerated(Boolean.TRUE.equals(req.aiGenerated()));
        media.setEditorialCaption(req.editorialCaption());
        media.setEventDate(req.eventDate());
        media.setEditorialLocation(req.editorialLocation());
        media.setEventSubjectName(req.eventSubjectName());
        media.setEditorialNotes(req.editorialNotes());
    }

    private void applyDevice(MediaAsset media, MediaRequest req, UUID ownerId, boolean creating) {
        if (req.captureDeviceId() == null) {
            // Capture device is required (VAL-005); allow null only if already set on update.
            if (creating || media.getCaptureDevice() == null) {
                throw ApiException.badRequest("Capture device is required");
            }
            return;
        }
        CaptureDevice device = captureDeviceRepository.findById(req.captureDeviceId())
                .orElseThrow(() -> ApiException.badRequest("Capture device not found"));
        if (creating && !device.isActive()) {
            throw ApiException.badRequest("Capture device is inactive and cannot be used for new media");
        }
        media.setCaptureDevice(device);
    }

    private void applyLens(MediaAsset media, MediaRequest req) {
        if (req.lensId() == null) {
            media.setLens(null);
            return;
        }
        Lens lens = lensRepository.findById(req.lensId())
                .orElseThrow(() -> ApiException.badRequest("Lens not found"));
        media.setLens(lens);
    }

    /** Concepts must belong to the same owner (BR-012). */
    private void applyConcepts(MediaAsset media, MediaRequest req, UUID ownerId) {
        media.getConcepts().clear();
        if (req.conceptIds() == null || req.conceptIds().isEmpty()) {
            return;
        }
        List<UUID> ids = req.conceptIds().stream().distinct().toList();
        List<Concept> owned = conceptRepository.findByOwnerIdAndIdIn(ownerId, ids);
        if (owned.size() != ids.size()) {
            throw ApiException.badRequest("One or more concepts are invalid or not owned by you");
        }
        media.getConcepts().addAll(owned);
    }

    /** Keywords are normalized and get-or-created per owner; duplicates collapse (VAL-009). */
    private void applyKeywords(MediaAsset media, MediaRequest req, UUID ownerId) {
        media.getKeywords().clear();
        if (req.keywords() == null || req.keywords().isEmpty()) {
            return;
        }
        Set<String> seen = new LinkedHashSet<>();
        List<Keyword> resolved = new ArrayList<>();
        for (String raw : req.keywords()) {
            String normalized = Keyword.normalize(raw);
            if (normalized == null || normalized.isEmpty() || !seen.add(normalized)) {
                continue;
            }
            Keyword keyword = keywordRepository
                    .findByOwnerIdAndNormalizedValue(ownerId, normalized)
                    .orElseGet(() -> keywordRepository.save(new Keyword(ownerId, raw.trim(), normalized)));
            resolved.add(keyword);
        }
        media.getKeywords().addAll(resolved);
    }

    /** Enforces the Ready-for-Upload gate (VAL-008); target-site check added with submissions. */
    private void validateStatusRequirements(MediaAsset media) {
        if (media.getWorkflowStatus() != WorkflowStatus.READY) {
            return;
        }
        List<String> missing = new ArrayList<>();
        if (blankToNull(media.getThumbnailKey()) == null) missing.add("thumbnail");
        if (media.getCaptureDevice() == null) missing.add("capture device");
        if (media.getKeywords().isEmpty()) missing.add("keywords");
        if (media.getContentUsageType() == null) missing.add("content usage type");
        if (!missing.isEmpty()) {
            throw ApiException.badRequest("Cannot mark Ready for Upload; missing: " + String.join(", ", missing));
        }
    }

    private static String blankToNull(String s) {
        return (s == null || s.isBlank()) ? null : s;
    }
}
